### ISSUE TITLE
Double // in file name

### ISSUE THREAD

**Issue by matdave** [Sterc/FileSluggy#10]
I just noticed this.  If your Media Source is set up with a base path starting with / e.g. "/assets/site/" then the Directory sanitization won't work.  It fails at: 

<pre>
$source->renameContainer(str_replace($basePath, '', $directory), $dirName);
</pre>

Because /home/user/public_html/assets/site/ does not contain /home/user/public_html//assets/site/ .

**Comment by Flowan** [comment]
We will have a look at it. We will try to add this in the next release.

**Comment by joeke** [comment]
I've added the code from your PR in the latest 1.3.1 release https://modx.com/extras/package/filesluggy. Thanks again for your contribution, Mat! Much appreciated!
