### ISSUE TITLE
Question: why the test for page action?

### ISSUE THREAD

**Issue by jcdm** [Sterc/FileSluggy#15]
Question: in lines 48-50 of the plugin there's some tests to check via URL matching that the upload is happening on a page that is either creating or updating a resource or in the media browser.

This precludes anyone from having their uploads sanitised should they choose to upload via the file tree on any other page in the manager.

I'm just wondering what the reasoning for this test is - what issues is it there to avoid?

**Comment by joeke** [comment]
Hi Josh
We've added that recently to allow FileSluggy to play well with other plugins that use file create/upload abilities, like for example ContentBlocks. To be honest we've overlooked the fact that you can use the file/dir create/upload functions from basically every page inside the manager via the file tree.
I'll discuss this with my colleagues next week, and we'll get back to you asap.

**Comment by joeke** [comment]
@jcdm New release 1.3.1 is just out, where removed the check for page action in favor of using a custom system event. Get it here: https://modx.com/extras/package/filesluggy
