### ISSUE TITLE
Fatal error on PHP 8: Array and string offset access syntax with curly braces is no longer supported

### ISSUE THREAD

**Issue by Mark-H** [Sterc/FileSluggy#29]
( ! ) Fatal error: Array and string offset access syntax with curly braces is no longer supported in core/components/filesluggy/model/filesluggy/filesluggy.class.php on line 237

Note you need MODX 2.8.2 (read: 2.x branch as of today) for MODX to not break in PHP8.

**Comment by deJaya** [comment]
Seeing this too 👍

**Comment by mediengaarage** [comment]
I have the same problem!
MODX 2.8.3
PHP 8.1

**Comment by sebastian-marinescu** [comment]
I had this error, too, all of a sudden. 
Pushed a fix. I hope it gets published soon :crossed_fingers:
