### ISSUE TITLE
Installing FileSluggy 3.0.0 causing error in MODX 2.8.5

### ISSUE THREAD

**Issue by travisbotello** [Sterc/FileSluggy#35]
Trying to upgrade/install FileSluggy 3.0.0 in MODX 2.8.5 causing empty installing modal.

![Screenshot 2023-03-20 at 11 30 23](https://user-images.githubusercontent.com/1157380/226314067-d5347af6-96b0-4424-905f-bc4d6cbd9749.png)

**Comment by mindeffects** [comment]
Yep, confirmed. This empty modal is what brought me here. ;-)
Maybe only the setup is broken…?!
If the extra was updated BEFORE updating to modx 2.8.5, is it still functional AFTER the update to 2.8.5?

**Comment by gpsietzema** [comment]
@mindeffects We remove it in all our 3.x instances, because it's handled in the core now. Not exactly the same, but it results in the same: better filenames.

**Comment by travisbotello** [comment]
> @mindeffects We remove it in all our 3.x instances, because it's handled in the core now. Not exactly the same, but it results in the same: better filenames.

So what does that mean for the installation error of FileSluggy 3.0.0 in MODX 2.8.x?

**Comment by gpsietzema** [comment]
@mindeffects @travisbotello I 3.0.0 doesn't work with 2.* I think, so I modified modx.com for a bit to accomplish that. 3.0 is now cancelled and you can't install it anymore on 2 or 3. I modified the older versions only to install on 2.8.*

https://modx.com/extras/package/filesluggy

**Comment by travisbotello** [comment]
> @mindeffects @travisbotello I 3.0.0 doesn't work with 2.* I think, so I modified modx.com for a bit to accomplish that. 3.0 is now cancelled and you can't install it anymore on 2 or 3. I modified the older versions only to install on 2.8.*
> 
> https://modx.com/extras/package/filesluggy

Confirmed. The update is no longer available for MODX 2.* :)
