### ISSUE TITLE
Wrong assets_path in modx_namespaces table

### ISSUE THREAD

**Issue by vierkantemeter** [Sterc/FileSluggy#5]
I guess it does not stop filesluggy from working, but I saw in the table modx_namespaces a wrong assets_path is set:

```
/Users/friso/Sites/modx/filesluggy/assets/components/filesluggy/
```

Filesluggy 1.1
MODX 2.2.15

**Comment by joeke** [comment]
A bit late to the party, but nevertheless: this should be fixed in the latest 1.3.1 version: https://modx.com/extras/package/filesluggy
