### ISSUE TITLE
cleaned-cleaned-cleaned-cleaned foldername bug

### ISSUE THREAD

**Issue by Lefthandmedia** [Sterc/FileSluggy#9]
when creating a new folder the foldername is preceded by the word 'cleaned-' about 30 times.

**Comment by Flowan** [comment]
We will have a look at it. We will try to add this in the next release.

**Comment by christianseel** [comment]
I'm having the same issue with the latest release from today…
"Eins Tüsn" became "56a149f7607a2-56a149f75f61f-56a149f75e4a9-56a149f75d1da-56a149f75b4a1-56a149f75a2d9-56a149f759607-56a149f75865f-56a149f7570d9-56a149f755453-56a149f753ddd-56a149f75181c-56a149f750010-56a149f74ea86-56a149f74d9ab-56a149f74c5c3-56a149f74a1ba-eins-tusn" as a foldername in the MODX media browser

**Comment by joeke** [comment]
@Lefthandmedia @christianseel This should be fixed now in the latest 1.3.1 release: https://modx.com/extras/package/filesluggy
Closing this for now. Please feel free to re-open this issue if you're still experiencing this problem.
